'use strict';
/* Rotary Guard Protocol V2.9 (RGP V2.9)
   Guardrail mechanisms reformulated for local browser-side AI-content filtering.
   Classification/policy only: no DOM, storage, network, or action authority. */
(() => {
  const ACTION=Object.freeze({PASS:'PASS',WATCH:'WATCH',FILTER:'FILTER',CONFLICT:'CONFLICT',INSUFFICIENT:'INSUFFICIENT'});
  const norm=s=>String(s||'').normalize('NFKC').replace(/[\u200B-\u200D\u2060\uFEFF]/g,'').toLowerCase().replace(/[\s_-]+/g,' ').trim();
  const ev=(guard,group,weight,reason,polarity=1,tier='FAST')=>Object.freeze({guard,group,weight:Math.max(0,Math.min(8,Number(weight)||0)),reason:String(reason||''),polarity:polarity<0?-1:1,tier});
  const RX=Object.freeze({
    reference:/\b(news|report|research|study|policy|copyright|regulation|ethics|lawsuit|analysis|explained|what is|what does|how to spot|how to detect|detect(?:ing|ion)?|history of|future of|year ahead|interview|review|fact check|guide to identifying)\b/,
    disclosure:/\b(?:ai|artificial intelligence)[ -]?(?:generated|created|made|assisted|produced)\b|\b(?:generated|created|made|produced)\s+(?:by|with|using)\s+(?:ai|artificial intelligence)\b|\bsynthetic\s+(?:media|image|photo|video|audio|voice|content)\b/,
    media:/\b(?:ai|artificial intelligence|generative ai)\s+(?:(?:generated|stock|future|synthetic)\s+)?(?:image|photo|art|artwork|illustration|portrait|video|animation|audio|music|song|voice|text|story|article|content)s?\b|\b(?:image|photo|art|illustration|portrait|video|animation|audio|music|song|voice|content)s?\b.{0,45}\b(?:ai[- ]generated|generated by ai|generated with ai|synthetic)\b/,
    generator:/\b(?:ai|artificial intelligence)\s+(?:image|photo|art|video|animation|audio|music|song|voice|text|content)\s+(?:generator|maker|creator|studio|tool)s?\b|\b(?:text to image|text to video|image to video|image to image|text to speech|voice clon(?:e|ing))\b/,
    cta:/\b(?:generate|create|make|turn|transform)\b.{0,55}\b(?:image|photo|art|video|animation|music|song|voice|audio|content)s?\b.{0,55}\b(?:ai|artificial intelligence)\b|\b(?:ai|artificial intelligence)\b.{0,55}\b(?:generate|create|make)\b/,
    source:/\b(?:midjourney|dall[ -]?e|openai|chatgpt images|stable diffusion|stability ai|runway|leonardo ai|ideogram|pika|suno|udio|elevenlabs)\b/,
    sourceUrl:/\b(?:midjourney\.com|openai\.com|chatgpt\.com|stability\.ai|runwayml\.com|leonardo\.ai|ideogram\.ai|pika\.art|suno\.com|udio\.com|elevenlabs\.io)\b/
  });
  function fastRail(c,out){
    const zeroTopic=c.sensitivity==='zero-ai' && ( /\b(?:ai|artificial intelligence|generative ai|synthetic media|large language models?|llms?|machine learning|deep learning|foundation models?|generative models?|prompt engineering|ai agents?|agentic ai)\b/.test(c.combined) || /\b(?:chatgpt|dall[ -]?e|midjourney|stable diffusion|stability ai|runwayml|leonardo ai|ideogram|pika|suno|udio|elevenlabs|openai|anthropic)\b/.test(c.combined) || RX.sourceUrl.test(c.hrefs) || /\banthropic\.com\b/.test(c.hrefs) );
    if(zeroTopic)out.push(ev('topic','zero-ai-topic',5,'Zero-AI explicit AI subject-matter exclusion',1,'CONTEXT'));
    if(RX.disclosure.test(c.combined))out.push(ev('provenance','explicit-disclosure',7,'explicit AI/synthetic generation disclosure'));
    if(RX.generator.test(c.combined))out.push(ev('generator','generator-modality',7,'explicit AI generator/modality'));
    if(/\b(?:top|best|recommended|popular)\b.{0,40}\bai\b.{0,35}\b(?:generator|tool)s?\b/.test(c.combined))out.push(ev('generator','generator-list',7,'AI generator recommendation list'));
    if(RX.reference.test(c.text))out.push(ev('reference','reference-context',zeroTopic?2:6,'news/research/educational/reference context',-1));
    if(/^\s*(?:how|what|why|when|where|who|can|could|should|is|are|does|do|will|would)\b.{0,240}\?/.test(c.text))out.push(ev('reference','question-context',zeroTopic?2:6,'question/reference context',-1));
  }
  function contextRail(c,out){
    if(RX.media.test(c.combined))out.push(ev('media','ai-media-semantics',4,'AI media/content semantics',1,'CONTEXT'));
    if(/\b(?:ai|artificial intelligence)\b.{0,55}\b(?:stock photos?|stock images?|images?|photos?|art|illustrations?|portraits?|videos?|animations?|audio|music|voices?)\b/.test(c.combined))out.push(ev('media','ai-media-proximity',4,'AI-associated media proximity',1,'CONTEXT'));
    if(RX.cta.test(c.combined))out.push(ev('promotion','creation-cta',5,'AI creation call-to-action',1,'CONTEXT'));
    if(c.actionable&&RX.cta.test(c.combined))out.push(ev('structure','actionable-context',2,'actionable AI creation context',1,'CONTEXT'));
    if(RX.source.test(c.combined)||RX.sourceUrl.test(c.hrefs))out.push(ev('source','ai-service-source',3,'AI-service/source provenance',1,'CONTEXT'));
    if(/\b(?:robot|robotics|cgi|3d render|digital art|vfx)\b/.test(c.text)&&!RX.disclosure.test(c.combined)&&!RX.generator.test(c.combined)&&!RX.media.test(c.combined)&&!/\b(?:ai|artificial intelligence)\b.{0,55}\b(?:stock photos?|stock images?|images?|photos?|art|illustrations?|videos?|animations?)\b/.test(c.combined))out.push(ev('reference','visual-topic-guard',4,'ordinary CGI/robot/digital-art context',-1,'CONTEXT'));
  }
  // Shadow rail: research-only observations. Weight is always zero and cannot influence policy.
  function shadowRail(c){
    const observations=[];
    const words=c.text.split(/\s+/).filter(Boolean);
    if(words.length>=40){
      const unique=new Set(words).size/words.length;
      observations.push(Object.freeze({guard:'shadow-statistical',signal:'lexical-diversity',value:Number(unique.toFixed(3)),weight:0,authority:'SHADOW'}));
    }
    return observations;
  }
  function inspect(ctx={}){
    const text=norm(ctx.text), metadata=norm(ctx.metadata), hrefs=norm(ctx.hrefs), combined=`${text} ${metadata}`.trim();
    const c={text,metadata,hrefs,combined,actionable:ctx.actionable===true,sensitivity:ctx.sensitivity||'extreme'}; const out=[];
    fastRail(c,out); contextRail(c,out);
    return Object.freeze({evidence:out,shadow:shadowRail(c)});
  }
  const familyOf=x=>({provenance:'PROVENANCE',generator:'MODALITY',media:'SEMANTIC',promotion:'INTENT',structure:'STRUCTURE',source:'SOURCE',reference:'REFERENCE',topic:'TOPIC'}[x.guard]||'OTHER');
  function detectMedium(hay=''){
    hay=String(hay).toLowerCase();
    if(/voice|audio|music|song|speech/.test(hay))return 'AUDIO';
    if(/video|animation/.test(hay))return 'VIDEO';
    if(/image|photo|art|illustration|portrait/.test(hay))return 'IMAGE';
    if(/text|story|article|content/.test(hay))return 'TEXT';
    if(/generator|service|source/.test(hay))return 'SERVICE';
    return 'GENERIC';
  }
  function mediumOf(items=[]){
    return detectMedium(items.map(x=>`${x.reason} ${x.group}`).join(' '));
  }
  const mediumThreshold=Object.freeze({IMAGE:7,VIDEO:7,AUDIO:6,TEXT:8,SERVICE:7,GENERIC:7});
  function classify(items=[],mediumHint='',sensitivity='balanced'){
    const pos=items.filter(x=>x.polarity>0),neg=items.filter(x=>x.polarity<0);
    const groups=new Set(pos.map(x=>x.group)); const families=new Set(pos.map(familyOf));
    const positive=pos.reduce((n,x)=>n+x.weight,0),negative=neg.reduce((n,x)=>n+x.weight,0);
    const explicit=pos.some(x=>['explicit-disclosure','generator-modality','generator-list'].includes(x.group));
    const medium=mediumHint||mediumOf(pos); const baseThreshold=mediumThreshold[medium]||7; const shift=({conservative:1,balanced:0,high:-1,maximum:-2,extreme:-3,'zero-ai':-4})[sensitivity]??0; const floor=({'zero-ai':2,extreme:3})[sensitivity]??4; const threshold=Math.max(floor,baseThreshold+shift); const explicitNeed=({conservative:6,balanced:5,high:4,maximum:3,extreme:2,'zero-ai':1})[sensitivity]??5;
    const conflict=positive>=5&&negative>=5; let action=ACTION.INSUFFICIENT;
    if(conflict)action=ACTION.CONFLICT;
    else if(explicit&&positive-negative>=explicitNeed)action=ACTION.FILTER;
    // Diversity gate: non-explicit FILTER requires corroboration from at least two evidence families.
    else if(groups.size>=2&&families.size>=2&&positive-negative>=threshold)action=ACTION.FILTER;
    // Extreme permits a single strong AI-media semantic family when the evidence is explicit enough.
    else if(sensitivity==='extreme'&&positive>=4&&negative===0&&pos.some(x=>['ai-media-semantics','ai-media-proximity','creation-cta','ai-service-source'].includes(x.group)))action=ACTION.FILTER;
    // Zero-AI is opt-in: identifiable AI-associated content is filtered unless meaningful reference counter-evidence exists.
    else if(sensitivity==='zero-ai'&&positive>=3&&negative<5)action=ACTION.FILTER;
    else if(positive>=3)action=ACTION.WATCH;
    else if(negative>0)action=ACTION.PASS;
    const kind=pos.some(x=>['generator-modality','generator-list'].includes(x.group))?'AI_GENERATOR':pos.some(x=>x.group==='explicit-disclosure')?'AI_GENERATED_CONTENT':pos.some(x=>x.group==='creation-cta')?'AI_PROMOTION':pos.length?'AI_CONTENT':'REFERENCE_OR_UNKNOWN';
    return Object.freeze({action,kind,medium,threshold,positive,negative,independent:groups.size,diversity:families.size,families:[...families],conflict,evidence:items.slice(0,24)});
  }
  function evaluate(ctx){const inspected=inspect(ctx);const medium=detectMedium(`${ctx?.text||''} ${ctx?.metadata||''} ${ctx?.hrefs||''}`);const sensitivity=['conservative','balanced','high','maximum','extreme','zero-ai'].includes(ctx?.sensitivity)?ctx.sensitivity:'extreme';const result=classify(inspected.evidence,medium,sensitivity);return Object.freeze({...result,sensitivity,shadow:inspected.shadow});}
  const api=Object.freeze({VERSION:'2.9',ACTION,normalize:norm,inspect,classify,evaluate});
  globalThis.RotaryGuardV2=api;
  globalThis.RotaryGuardV1=api; // compatibility alias for inherited regression harnesses
})();
