'use strict';
const $=id=>document.getElementById(id);
const ids=['enabled','aiContent','aiLabels','aiPromotion','scamClaims','explain','socialYoutube','socialTiktok','socialInstagram','socialFacebook','socialThreads','socialX','socialReddit','socialLinkedin','socialTwitch','socialDiscord','socialPinterest','socialBluesky','socialMastodon','socialTumblr','aiSiteBlock'];
const el=Object.fromEntries([...ids,'placeholderMode','placeholderTreatment','placeholderDensity','words','status','statusTitle','statusText','save'].map(id=>[id,$(id)]));
function renderPower(on){el.status.textContent=on?'ON':'OFF';el.statusTitle.textContent=on?'Protection Active':'Protection Paused';el.statusText.textContent=on?'Local Zero-AI filtering on this device.':'Content is currently left visible.';document.body.classList.toggle('paused',!on);}
async function load(){const r=await browser.runtime.sendMessage({type:'ROTARY_GET_STATE'});if(!r||!r.ok)return;const s=r.state;el.enabled.checked=!!s.enabled;el.aiContent.checked=s.categories.aiContent!==false;el.aiLabels.checked=!!s.categories.aiLabels;el.aiPromotion.checked=!!s.categories.aiPromotion;el.scamClaims.checked=!!s.categories.scamClaims;el.explain.checked=!!s.explain;el.socialYoutube.checked=s.socialSites?.youtube!==false;el.socialTiktok.checked=s.socialSites?.tiktok!==false;el.socialInstagram.checked=s.socialSites?.instagram!==false;el.socialFacebook.checked=s.socialSites?.facebook!==false;el.socialThreads.checked=s.socialSites?.threads!==false;el.socialX.checked=s.socialSites?.x!==false;el.socialReddit.checked=s.socialSites?.reddit!==false;el.socialLinkedin.checked=s.socialSites?.linkedin!==false;el.socialTwitch.checked=s.socialSites?.twitch!==false;el.socialDiscord.checked=s.socialSites?.discord!==false;el.socialPinterest.checked=s.socialSites?.pinterest!==false;el.socialBluesky.checked=s.socialSites?.bluesky!==false;el.socialMastodon.checked=s.socialSites?.mastodon!==false;el.socialTumblr.checked=s.socialSites?.tumblr!==false;el.aiSiteBlock.checked=s.aiSiteBlock===true;el.placeholderMode.value=s.placeholderMode==='compact'?'compact':'minimal';el.placeholderTreatment.value=s.placeholderTreatment||'blur';el.placeholderDensity.value=s.placeholderDensity||'normal';el.words.value=(s.mutedWords||[]).join('\n');renderPower(!!s.enabled);}
el.enabled.addEventListener('change',()=>renderPower(el.enabled.checked));
el.save.addEventListener('click',async()=>{const r=await browser.runtime.sendMessage({type:'ROTARY_GET_STATE'});if(!r||!r.ok)return;const s=r.state;await browser.storage.local.set({enabled:el.enabled.checked,level:'zero-ai',explain:el.explain.checked,placeholderMode:el.placeholderMode.value==='compact'?'compact':'minimal',placeholderTreatment:el.placeholderTreatment.value,placeholderDensity:el.placeholderDensity.value,categories:{...s.categories,aiContent:el.aiContent.checked,aiLabels:el.aiLabels.checked,aiPromotion:el.aiPromotion.checked,scamClaims:el.scamClaims.checked},socialSites:{...s.socialSites,youtube:el.socialYoutube.checked,tiktok:el.socialTiktok.checked,instagram:el.socialInstagram.checked,facebook:el.socialFacebook.checked,threads:el.socialThreads.checked,x:el.socialX.checked,reddit:el.socialReddit.checked,linkedin:el.socialLinkedin.checked,twitch:el.socialTwitch.checked,discord:el.socialDiscord.checked,pinterest:el.socialPinterest.checked,bluesky:el.socialBluesky.checked,mastodon:el.socialMastodon.checked,tumblr:el.socialTumblr.checked},aiSiteBlock:el.aiSiteBlock.checked,mutedWords:el.words.value.split('\n').map(x=>x.trim()).filter(Boolean).slice(0,100)});renderPower(el.enabled.checked);el.save.textContent='Saved';setTimeout(()=>{el.save.textContent='Save changes';},700);});
load().catch(()=>{el.status.textContent='—';el.statusTitle.textContent='Status unavailable';el.statusText.textContent='Reload the extension to reconnect.';});
